# Generated by Django 4.2.24 on 2025-09-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dds.category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dds.status'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dds.subcategory'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dds.type'),
        ),
    ]
