# Generated by Django 4.2.24 on 2025-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_alter_record_category_alter_record_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(verbose_name='Дата записи'),
        ),
    ]
