# Generated by Django 4.2.24 on 2025-10-01 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи'),
        ),
    ]
